// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: album.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AlbumClient is the client API for Album service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlbumClient interface {
	ListAlbum(ctx context.Context, in *ListAlbumReq, opts ...grpc.CallOption) (*ListAlbumReply, error)
}

type albumClient struct {
	cc grpc.ClientConnInterface
}

func NewAlbumClient(cc grpc.ClientConnInterface) AlbumClient {
	return &albumClient{cc}
}

func (c *albumClient) ListAlbum(ctx context.Context, in *ListAlbumReq, opts ...grpc.CallOption) (*ListAlbumReply, error) {
	out := new(ListAlbumReply)
	err := c.cc.Invoke(ctx, "/Album/ListAlbum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlbumServer is the server API for Album service.
// All implementations must embed UnimplementedAlbumServer
// for forward compatibility
type AlbumServer interface {
	ListAlbum(context.Context, *ListAlbumReq) (*ListAlbumReply, error)
	mustEmbedUnimplementedAlbumServer()
}

// UnimplementedAlbumServer must be embedded to have forward compatible implementations.
type UnimplementedAlbumServer struct {
}

func (UnimplementedAlbumServer) ListAlbum(context.Context, *ListAlbumReq) (*ListAlbumReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlbum not implemented")
}
func (UnimplementedAlbumServer) mustEmbedUnimplementedAlbumServer() {}

// UnsafeAlbumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlbumServer will
// result in compilation errors.
type UnsafeAlbumServer interface {
	mustEmbedUnimplementedAlbumServer()
}

func RegisterAlbumServer(s grpc.ServiceRegistrar, srv AlbumServer) {
	s.RegisterService(&Album_ServiceDesc, srv)
}

func _Album_ListAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlbumReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServer).ListAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Album/ListAlbum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServer).ListAlbum(ctx, req.(*ListAlbumReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Album_ServiceDesc is the grpc.ServiceDesc for Album service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Album_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Album",
	HandlerType: (*AlbumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAlbum",
			Handler:    _Album_ListAlbum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "album.proto",
}
